### PR TITLE
Fix the conn_sup supervision specification

### LINKED ISSUE #34: The turtle conn process is a worker and not a supervisor
Yet, the code says otherwise. This is an easy fix for subtle correctness.

### PR DESCRIPTION
**Pull request by gausby**
Fixes #34 - The turtle conn process is a worker and not a supervisor.

I have also upgraded the specification itself to the new map-based supervision specification format. This is also the format used by the janitor specification a couple of lines above, so I do not think there is any backwards compatibility concerns.

### CODE REVIEW

File: src/turtle_sup.erl [hunk 1]
```diff
@@ -47,7 +47,11 @@ configure_connectors() ->
...
-    {Name,
-        {turtle_conn, start_link, [Name, Ps]},
-        permanent, infinity, supervisor, [turtle_conn_sup]}.
+conn_sup(#{conn_name := Name} = Ps) ->
+    #{ id => Name,
+       start => {turtle_conn, start_link, [Name, Ps]},
+       restart => permanent,
+       shutdown => infinity,
+       type => worker,
+       modules => [turtle_conn_sup]
```
Comment (jlouis) [inline src/turtle_sup.erl]: This should be `turtle_conn`, that module is gone.
